services:
  app:
    build:
      context: .
      args:
        GITHUB_ACTOR: ${GITHUB_ACTOR:-}
      secrets:
        - github_token
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/${DB_NAME:-booking}
      DB_USERNAME: ${DB_USERNAME:-bookinguser}
      DB_PASSWORD: ${DB_PASSWORD:-123456}
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME:-bookinguser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123456}
      POSTGRES_DB: ${DB_NAME:-booking}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

secrets:
  github_token:
    environment: GITHUB_TOKEN