spring.datasource.url=jdbc:postgresql://postgres:5432/booking
spring.jpa.properties.hibernate.default_schema=public
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.username=bookinguser
spring.datasource.password=123456
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
