# Datasource Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/booking}
spring.datasource.username=${DB_USERNAME:bookinguser}
spring.datasource.password=${DB_PASSWORD:123456}
# JPA Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
# Logging
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG